### ISSUE TITLE
small man page issues 

### ISSUE THREAD

**Issue by ghudgins** [flox/flox#1018]
- [x] `flox containerize` needs an experimental warning #1020 
- [x] we list `-r` as an option for `flox delete` even though it emits a not yet implemented error #1020
- [x] `flox edit -f` is documented twice #1020

**Comment by mkenigs** [comment]
I think this can be closed

**Comment by ghudgins** [comment]
thank you! verified
