### ISSUE TITLE
feat: honor meta.outputsToInstall, add ability to install by individual package output

### ISSUE THREAD

**Issue by limeytexan** [flox/flox#1363]
We currently build an environment including all outputs when installing a package. This can be problematic, particularly when non-default outputs are large (e.g. I've seen build logs recorded as distinct outputs) or contain collisions with other outputs produced by the package (e.g. when a "profiling" package output provides an alternative instrumented version of a thing).

To avoid the issues described above Nix already provides the `meta.outputsToInstall` attribute, and the `nix profile` command also provides a way to install by individual package output when wanting to install something other than the default set. 

This issue is expected to require the following:

- [ ] come up with `manifest.toml` syntax for specifying individual outputs
    - by default, the set of outputs should be set exactly as implemented by `nix profile`, which IIRC is to use `meta.outputsToInstall` if defined, and otherwise fall back to the "first" output which is customarily "out", but not always(?).  (I hope I'm remembering that right ... please correct if I have that wrong!)
    - users should also able to enumerate the specific outputs to install, which carries with it a UX decision to be made:
        - this can either be absolute, and the specified list will _replace_ the default `outputsToInstall`
        - or relative, in which case the syntax will have to support additions and subtractions from the default `outputsToInstall`
- [ ] update the rust CLI code to parse and understand the modelling of individual outputs in the process of locking the manifest
- [ ] update user-facing documentation regarding the specification of individual outputs in `manifest.toml`

**Comment by mkenigs** [comment]
Thanks for writing that down @limeytexan!

I think for clarity we should split this into two parts:
1. Add an option to decide which outputs to install. It's pretty clear we need to do that.
2. Revisit the decision to default to all `outputs` rather than `outputsToInstall`. That's more of a design/product decision.

>     * [ ]  update the imperative `install` command to understand the installation of additional output types

I think to start this should be a `flox edit` only option, and then depending on how that's received we can decide if we need to add it to `install`

**Comment by mkenigs** [comment]
We'll come back to this once the manifest format is stable

**Comment by ysndr** [comment]
dup of https://github.com/flox/flox/issues/1838?

**Comment by limeytexan** [comment]
> dup of #1838

The timestamps would imply the opposite, but yes these are the same issue.

Recent progress is that the new buildenv (only just pressed into service with #2311) fully supports `outputsToInstall`, so the remaining work on this issue is around the UX of the manifest, and planning for a data migration as we upgrade manifests from version 1 to the "outputs-aware" version 2 schema.

**Comment by limeytexan** [comment]
An example of a package that employs a large number of outputs with only a single output to install:
```
nix-repl> :b nomad-autoscaler

This derivation produced the following outputs:
  aws_asg -> /nix/store/0bkgs58x07q5qvcqmyh2hgjlnmm9g6s0-nomad-autoscaler-0.3.6-aws_asg
  azure_vmss -> /nix/store/zvfq8ks3pdyw90w6lfbkf6zm9h20zc89-nomad-autoscaler-0.3.6-azure_vmss
  bin -> /nix/store/hvvd360vz1rxp0xg4f7j01sm37z67yrp-nomad-autoscaler-0.3.6-bin
  datadog -> /nix/store/6nc0milm2p58kklzjxd73a3kq3779ada-nomad-autoscaler-0.3.6-datadog
  fixed_value -> /nix/store/jvx9m1dyh6myrwlffk0khfp5m1dxw1qp-nomad-autoscaler-0.3.6-fixed_value
  gce_mig -> /nix/store/31xi11qyy1amb1gnlia51kj3i9ckabdl-nomad-autoscaler-0.3.6-gce_mig
  nomad_apm -> /nix/store/hglyxnxmg1b5ri1041mawihmyxri9zg6-nomad-autoscaler-0.3.6-nomad_apm
  nomad_target -> /nix/store/51wxin1p709c4v1r4742k2kh8h5jw253-nomad-autoscaler-0.3.6-nomad_target
  out -> /nix/store/pn8r5r6sixic6l70ixk41ml955svb4wi-nomad-autoscaler-0.3.6
  pass_through -> /nix/store/qw0h0zjwhg2x2ap1j0k7pc55rymzi1cs-nomad-autoscaler-0.3.6-pass_through
  prometheus -> /nix/store/yqd775sdhvvk4paa326xhmsd80nbc6vn-nomad-autoscaler-0.3.6-prometheus
  target_value -> /nix/store/m3m9ny4q4bg1fxw657y5551cv44bzwbz-nomad-autoscaler-0.3.6-target_value
  threshold -> /nix/store/830wb4wnl2lfl5c95lw9jarv33mlbd8c-nomad-autoscaler-0.3.6-threshold

nix-repl> nomad-autoscaler.meta.outputsToInstall
[ "bin" ]
```

The size of the closure for the one "bin" output is 42M:
```
brantley@ubuntu:~$ nix-store -qR /nix/store/hvvd360vz1rxp0xg4f7j01sm37z67yrp-nomad-autoscaler-0.3.6-bin | xargs du -shc | tail -1
42M     total
```

But the size of all of these outputs combined is >10x larger (note that `/tmp/asdf` is a copy of the full list of derivation outputs above):
```
brantley@ubuntu:~$ awk '{print $3}' /tmp/asdf | xargs nix-store -qR | sort -u | xargs du -shc | tail -1
471M    total
```

I selected the above example by collecting and analysing narinfo data for a single scrape of nixpkgs for x86_64-linux, in which there were 25225/72056 derivations for which `length(outputs) > length(meta.outputsToInstall)`. This particular example was one of the ones for which this delta was both the largest, and implied a high associated storage (i.e. performance) cost. I only performed this analysis by hand as shown above on a few examples; there will undoubtedly be many packages for which the cost implications are less, and a handful for which they will be even greater.

**Comment by limeytexan** [comment]
... and a _much_ more commonly used example carrying a 3x penalty:
```
nix-repl> :b curl                    

This derivation produced the following outputs:
  bin -> /nix/store/90y3x7xm92lazklx49jh73dmb0fwjap6-curl-8.8.0-bin
  debug -> /nix/store/nd7a3bm25yxgmzc204yhjq7xfwn0skky-curl-8.8.0-debug
  dev -> /nix/store/m2ix50bygbbyjj8p1gd2l2sb2grzc4pl-curl-8.8.0-dev
  devdoc -> /nix/store/h6imksjv3p1igaqqbba0qcywn8vlynds-curl-8.8.0-devdoc
  man -> /nix/store/590zd5x5sjk4r7m0hwkc0055fddbh9m9-curl-8.8.0-man
  out -> /nix/store/zi89x2zjl6d31bhs3y1x1bf440axrdh3-curl-8.8.0

nix-repl> curl.meta.outputsToInstall 
[ "bin" "man" ]

nix-repl> 
brantley@ubuntu:~$ nix-store -qR /nix/store/90y3x7xm92lazklx49jh73dmb0fwjap6-curl-8.8.0-bin /nix/store/590zd5x5sjk4r7m0hwkc0055fddbh9m9-curl-8.8.0-man | sort -u | xargs du -shc | tail -1
71M     total
brantley@ubuntu:~$ awk '{print $3}' /tmp/asdf | xargs nix-store -qR | sort -u | xargs du -shc | tail -1
224M    total
brantley@ubuntu:~$ 
```
